### ISSUE TITLE
Double "No silverware No napkins"

### ISSUE THREAD

**Issue by chrisjpowers** [TheBox193/fooda-tweaks#7]
When you return to a meal that you have previously ordered and marked as "No silverware No napkins", it is pre-populated in the text field already:

<img width="259" alt="screen shot 2018-04-09 at 8 07 09 am" src="https://user-images.githubusercontent.com/12329/38499520-70205a7c-3bcd-11e8-8226-294bf50ffad0.png">

If those boxes are checked, when you submit the form the "No silverware No napkins" text is doubled:

<img width="422" alt="screen shot 2018-04-09 at 8 07 17 am" src="https://user-images.githubusercontent.com/12329/38499538-89f278fe-3bcd-11e8-8f68-0610c0a3742c.png">

**Comment by TheBox193** [comment]
Now Resolved in v0.0.17 364a74d Thank you!
